application:
  host: 0.0.0.0
  port: 8080
  log_level: info
database:
  host: localhost
  port: 5432
  db_name: evolveme_db
jwt:
  secret: "change_this_to_a_strong_secret_in_production"
  expiration_hours: 24
redis:
  host: localhost
  port: 6379
minio:
  endpoint: http://localhost:9000
  bucket_name: riina-media
  region: us-east-1
  testing: false